CREATE TABLE USER (
CODE INT(6) AUTO_INCREMENT PRIMARY KEY,
USERNAME VARCHAR(30) NOT NULL,
PASSWORD VARCHAR(50) NOT NULL
);

CREATE TABLE CLIENT (
CODE INT(6) AUTO_INCREMENT PRIMARY KEY,
NAME VARCHAR(30) NOT NULL,
LASTNAME VARCHAR(50) NOT NULL,
EMAIL VARCHAR(50) NOT NULL,
PHONE VARCHAR(20) NOT NULL
);

CREATE TABLE CATEGORY (
CODE INT(6) AUTO_INCREMENT PRIMARY KEY,
NAME VARCHAR(30) NOT NULL,
TYPE VARCHAR(250) NOT NULL
);

CREATE INDEX IND_CATEGORY_NAME ON CATEGORY (NAME);

CREATE TABLE PRODUCT (
CODE INT(6) AUTO_INCREMENT PRIMARY KEY,
NAME VARCHAR(30) NOT NULL,
DESCRIPTION VARCHAR(250) NOT NULL,
CATEGORY_CODE INT(6) NOT NULL,
IMAGE BLOB NOT NULL,
FOREIGN KEY (CATEGORY_CODE) REFERENCES CATEGORY(CODE) ON DELETE CASCADE
);

CREATE INDEX IND_PRODUCT_NAME ON PRODUCT (NAME);

CREATE TABLE ORDER_PRODUCT (
CODE INT(6) AUTO_INCREMENT PRIMARY KEY,
AMOUNT INT(6) NOT NULL,
PRODUCT_CODE INT(6) NOT NULL,
CLIENT_CODE INT(6) NOT NULL,
ODER_NUMBER INT(6) NOT NULL,
FOREIGN KEY (PRODUCT_CODE) REFERENCES CLIENT(CODE) ON DELETE CASCADE,
FOREIGN KEY (CLIENT_CODE) REFERENCES PRODUCT(CODE) ON DELETE CASCADE
);

CREATE INDEX IND_ORDER_NAME ON ORDER_PRODUCT (ODER_NUMBER);